import { Transaction } from '@mysten/sui/transactions';
import { fromHex, toHex } from '@mysten/sui/utils';
import { createSuiClient, createSealClient, uploadToWalrus, loadKeypair, loadDeployedConfig, explorerLink } from './config.js';

async function main() {
  const suiClient = createSuiClient();
  const sealClient = createSealClient(suiClient);
  const keypair = loadKeypair();
  const { packageId, marketplaceId } = loadDeployedConfig();

  const price = 1_000_000n; // 0.001 SUI

  console.log('Creating cheap listing (0.001 SUI)...');
  const createTx = new Transaction();
  createTx.moveCall({
    target: `${packageId}::content_marketplace::create_listing`,
    arguments: [
      createTx.object(marketplaceId),
      createTx.pure.vector('u8', Array.from(new TextEncoder().encode('Getting Started with Sui Move - Starter Guide'))),
      createTx.pure.vector('u8', Array.from(new TextEncoder().encode('A beginner-friendly guide to Sui Move smart contracts. Only 0.001 SUI!'))),
      createTx.pure.u64(price),
      createTx.object('0x6'),
    ],
  });

  const createResult = await suiClient.signAndExecuteTransaction({ signer: keypair, transaction: createTx, options: { showObjectChanges: true } });
  await suiClient.waitForTransaction({ digest: createResult.digest });

  const listingChange = createResult.objectChanges?.find(
    (c) => c.type === 'created' && (c as any).objectType?.includes('ContentListing')
  );
  const capChange = createResult.objectChanges?.find(
    (c) => c.type === 'created' && (c as any).objectType?.includes('ListingCap')
  );
  const listingId = (listingChange as any)?.objectId as string;
  const capId = (capChange as any)?.objectId as string;
  console.log(`Listing: ${listingId}`);

  const content = `# Getting Started with Sui Move

This is a starter guide for the Sui Move language.

## What is Move?
Move is a safe, sandboxed language for digital assets on Sui.

## Key Concepts
- Objects are first-class citizens
- Ownership is enforced by the type system
- Transactions are atomic
- Shared objects enable permissionless access

## Why Sui?
Sui uses an object-centric data model that enables parallel transaction execution.

Generated by SealForge Agent.`;

  const contentBytes = new TextEncoder().encode(content);

  const nonce = crypto.getRandomValues(new Uint8Array(5));
  const listingIdBytes = fromHex(listingId.replace('0x', ''));
  const idBytes = new Uint8Array([...listingIdBytes, ...nonce]);
  const encryptionId = toHex(idBytes);

  console.log('Encrypting...');
  const { encryptedObject: encryptedBytes } = await sealClient.encrypt({
    threshold: 2, packageId, id: encryptionId, data: contentBytes,
  });

  console.log('Uploading to Walrus...');
  const blobId = await uploadToWalrus(encryptedBytes);
  console.log(`Blob: ${blobId}`);

  console.log('Updating listing...');
  const updateTx = new Transaction();
  updateTx.moveCall({
    target: `${packageId}::content_marketplace::update_blob_id`,
    arguments: [
      updateTx.object(capId),
      updateTx.object(listingId),
      updateTx.pure.vector('u8', Array.from(new TextEncoder().encode(blobId))),
    ],
  });
  await suiClient.signAndExecuteTransaction({ signer: keypair, transaction: updateTx, options: { showEffects: true } });

  console.log('\nDone! Cheap listing published:');
  console.log(`  Listing: ${explorerLink('object', listingId)}`);
  console.log(`  Price: 0.001 SUI`);
  console.log(`  Blob: ${blobId}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
